-- Provider-neutral communications adapter with Twilio selected for Phase 1.
create table if not exists public.bct_communication_provider_settings(id uuid primary key default gen_random_uuid(),provider text not null unique,enabled boolean not null default false,account_reference text,default_from_number text,proxy_service_reference text,recording_notice_text text not null default 'This call may be recorded by BCT Renovations for job coordination, quality, and documentation purposes.',created_at timestamptz not null default now(),updated_at timestamptz not null default now(),constraint bct_comm_provider_ck check(provider in('twilio','telnyx','other')));
alter table public.bct_communication_provider_settings enable row level security;
drop policy if exists "Communication provider settings admin only" on public.bct_communication_provider_settings;
create policy "Communication provider settings admin only" on public.bct_communication_provider_settings for all to authenticated using(public.is_bct_admin()) with check(public.is_bct_admin());
insert into public.bct_communication_provider_settings(provider,enabled) values('twilio',false) on conflict(provider) do nothing;
create or replace function public.bct_admin_activate_job_communications(p_project_id uuid,p_mode text default 'in_app') returns uuid language plpgsql security invoker set search_path=public,auth as $$
declare v_id uuid;v_contractor uuid;begin if not public.is_bct_admin() then raise exception 'BCT Admin required';end if;if p_mode not in('in_app','proxy_sms','proxy_voice') then raise exception 'Unsupported communication mode';end if;select assigned_contractor_id into v_contractor from public.bct_projects where id=p_project_id;if not found then raise exception 'Project not found';end if;if v_contractor is null then raise exception 'Assign and approve a contractor before activating contractor communications';end if;update public.bct_job_communication_sessions set status='ended',ended_at=now() where project_id=p_project_id and status='active';insert into public.bct_job_communication_sessions(project_id,assigned_contractor_id,communication_mode,created_by) values(p_project_id,v_contractor,p_mode,auth.uid()) returning id into v_id;return v_id;end $$;
revoke all on function public.bct_admin_activate_job_communications(uuid,text) from public,anon;grant execute on function public.bct_admin_activate_job_communications(uuid,text) to authenticated;
create or replace function public.bct_admin_log_arrival_notice(p_project_id uuid,p_body text) returns uuid language plpgsql security invoker set search_path=public,auth as $$
declare v_session uuid;v_id uuid;begin if not public.is_bct_admin() then raise exception 'BCT Admin required';end if;select id into v_session from public.bct_job_communication_sessions where project_id=p_project_id and status='active' order by created_at desc limit 1;if v_session is null then raise exception 'Activate BCT communications first';end if;insert into public.bct_job_communication_events(session_id,project_id,sender_role,event_type,body,created_by) values(v_session,p_project_id,'system','arrival_notice',coalesce(nullif(btrim(p_body),''),'Your BCT contractor is expected to arrive in approximately one hour.'),auth.uid()) returning id into v_id;return v_id;end $$;
revoke all on function public.bct_admin_log_arrival_notice(uuid,text) from public,anon;grant execute on function public.bct_admin_log_arrival_notice(uuid,text) to authenticated;
