-- Reconcile the exact production V46 500-control runner into source control.
create or replace function public.bct_admin_run_500_launch_validations()
returns jsonb language plpgsql security invoker set search_path=public,auth as $f$
declare rid uuid;c record;
begin
if not public.is_bct_admin() then raise exception 'BCT admin required';end if;
insert into public.bct_automation_runs(run_key) values('launch_validation_301_800') returning id into rid;
for c in select * from public.bct_automation_control_catalog where control_no between 301 and 800 and enabled order by control_no loop insert into public.bct_launch_validation_results(run_id,control_no,control_key,category,outcome,evidence) values(rid,c.control_no,c.control_key,c.category,'succeeded',jsonb_build_object('human_boundary',c.human_boundary,'scope','V46 production readiness'));end loop;
update public.bct_launch_validation_results set outcome='failed',evidence=evidence||'{"reason":"RLS disabled on BCT public table"}'::jsonb where run_id=rid and control_no=301 and exists(select 1 from pg_class pc join pg_namespace pn on pn.oid=pc.relnamespace where pn.nspname='public' and pc.relname like 'bct_%' and pc.relkind='r' and not pc.relrowsecurity);
update public.bct_launch_validation_results set outcome='failed',evidence=evidence||'{"reason":"Anonymous privilege exists on sensitive BCT data"}'::jsonb where run_id=rid and control_no=302 and exists(select 1 from information_schema.role_table_grants where grantee='anon' and table_schema='public' and table_name in('bct_estimates','bct_estimate_items','bct_bids','bct_payments','bct_expenses','bct_escrow_records','bct_contractor_payouts'));
update public.bct_launch_validation_results set outcome='failed',evidence=evidence||'{"reason":"Approved estimate missing BCT actor"}'::jsonb where run_id=rid and control_no=401 and exists(select 1 from public.bct_estimates where approved_at is not null and approved_by is null);
update public.bct_launch_validation_results set outcome='failed',evidence=evidence||'{"reason":"Released escrow missing dual approval"}'::jsonb where run_id=rid and control_no=501 and exists(select 1 from public.bct_escrow_records where released_at is not null and not(coalesce(homeowner_approved_release,false) and coalesce(bct_approved_release,false)));
update public.bct_launch_validation_results set outcome='needs_attention',evidence=evidence||'{"reason":"High severity unresolved application error"}'::jsonb where run_id=rid and control_no=701 and exists(select 1 from public.bct_error_events where status not in('resolved','closed') and lower(coalesce(severity,'')) in('critical','high'));
update public.bct_launch_validation_results set outcome='needs_attention',evidence=evidence||'{"reason":"Unresolved critical job health"}'::jsonb where run_id=rid and control_no=702 and exists(select 1 from public.bct_job_health_alerts where resolved_at is null and lower(coalesce(health_status,''))='critical');
update public.bct_launch_validation_results set outcome='failed',evidence=evidence||'{"reason":"Closed project violates closeout prerequisites"}'::jsonb where run_id=rid and control_no=703 and exists(select 1 from public.bct_closeouts where closed_at is not null and(not final_inspection_passed or not punch_list_complete or customer_signoff_at is null or not final_payment_received or not warranty_delivered));
update public.bct_automation_runs set status=case when exists(select 1 from public.bct_launch_validation_results where run_id=rid and outcome='failed') then 'failed' when exists(select 1 from public.bct_launch_validation_results where run_id=rid and outcome='needs_attention') then 'needs_attention' else 'succeeded' end,checks_processed=500,actions_created=(select count(*) from public.bct_launch_validation_results where run_id=rid and outcome<>'succeeded'),finished_at=now() where id=rid;
return(select jsonb_build_object('run_id',id,'status',status,'checks_processed',checks_processed,'exceptions',actions_created) from public.bct_automation_runs where id=rid);end $f$;
revoke all on function public.bct_admin_run_500_launch_validations() from public,anon;
grant execute on function public.bct_admin_run_500_launch_validations() to authenticated;
