-- V46 isolated Handyman operations. Additive only; do not apply to production.
alter table public.bct_handyman_applications
 add column if not exists background_check_consent_at timestamptz,
 add column if not exists background_check_ordered_at timestamptz,
 add column if not exists background_check_completed_at timestamptz,
 add column if not exists background_check_adverse_action_status text not null default 'not_started' check(background_check_adverse_action_status in('not_started','none','review_required','closed'));
create table if not exists public.bct_handyman_screening_events(
 id uuid primary key default gen_random_uuid(),handyman_application_id uuid not null references public.bct_handyman_applications(id) on delete cascade,
 provider text not null,provider_reference text,event_type text not null check(event_type in('authorized','ordered','scheduled','clear','consider','failed','adverse_action_opened','adverse_action_closed')),event_at timestamptz not null default now(),notes text,created_at timestamptz not null default now());
create index if not exists bct_handyman_screening_events_app_idx on public.bct_handyman_screening_events(handyman_application_id,event_at desc);
alter table public.bct_handyman_screening_events enable row level security; revoke all on public.bct_handyman_screening_events from anon,authenticated;
create table if not exists public.bct_handyman_assignments(
 id uuid primary key default gen_random_uuid(),handyman_application_id uuid not null references public.bct_handyman_applications(id) on delete cascade,
 bct_job_reference text not null,customer_code text,trade text,assignment_status text not null default 'offered' check(assignment_status in('offered','accepted','scheduled','in_progress','completed','cancelled','declined')),
 scheduled_for timestamptz,assigned_at timestamptz not null default now(),completed_at timestamptz,internal_notes text,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create index if not exists bct_handyman_assignments_app_idx on public.bct_handyman_assignments(handyman_application_id,assignment_status);
alter table public.bct_handyman_assignments enable row level security; revoke all on public.bct_handyman_assignments from anon,authenticated;
create or replace function public.bct_admin_handyman_credentials() returns setof public.bct_handyman_credentials language sql stable security definer set search_path=public,auth as $$ select c.* from public.bct_handyman_credentials c join public.bct_handyman_applications h on h.id=c.handyman_application_id where public.is_bct_admin() order by c.created_at desc $$;
revoke execute on function public.bct_admin_handyman_credentials() from public,anon; grant execute on function public.bct_admin_handyman_credentials() to authenticated;
create or replace function public.bct_admin_review_handyman_credential(p_credential_id uuid,p_status text,p_notes text) returns void language plpgsql security definer set search_path=public,auth as $$ begin if not public.is_bct_admin() then raise exception 'BCT Admin access required'; end if; if p_status not in('pending','verified','expiring','expired','rejected') then raise exception 'Invalid credential status'; end if; update public.bct_handyman_credentials set status=p_status,notes=nullif(trim(coalesce(p_notes,'')),''),verified_at=case when p_status='verified' then now() else verified_at end,verified_by=case when p_status='verified' then auth.uid() else verified_by end,updated_at=now() where id=p_credential_id; if not found then raise exception 'Handyman credential not found'; end if; end $$;
revoke execute on function public.bct_admin_review_handyman_credential(uuid,text,text) from public,anon; grant execute on function public.bct_admin_review_handyman_credential(uuid,text,text) to authenticated;
create or replace function public.bct_admin_create_handyman_assignment(p_handyman_application_id uuid,p_bct_job_reference text,p_customer_code text,p_trade text,p_scheduled_for timestamptz,p_internal_notes text) returns uuid language plpgsql security definer set search_path=public,auth as $$ declare v_id uuid; begin if not public.is_bct_admin() then raise exception 'BCT Admin access required'; end if; if not exists(select 1 from public.bct_handyman_applications where id=p_handyman_application_id and approval_status='approved' and background_check_status='clear' and application_status='approved') then raise exception 'Handyman must be BCT approved with a clear background check'; end if; insert into public.bct_handyman_assignments(handyman_application_id,bct_job_reference,customer_code,trade,scheduled_for,internal_notes) values(p_handyman_application_id,trim(p_bct_job_reference),nullif(trim(p_customer_code),''),nullif(trim(p_trade),''),p_scheduled_for,nullif(trim(p_internal_notes),'')) returning id into v_id; return v_id; end $$;
revoke execute on function public.bct_admin_create_handyman_assignment(uuid,text,text,text,timestamptz,text) from public,anon; grant execute on function public.bct_admin_create_handyman_assignment(uuid,text,text,text,timestamptz,text) to authenticated;
create or replace function public.bct_handyman_assignments_for_app(p_application_code text,p_email text) returns setof public.bct_handyman_assignments language sql stable security definer set search_path=public,auth as $$ select a.* from public.bct_handyman_assignments a join public.bct_handyman_applications h on h.id=a.handyman_application_id where upper(h.application_code)=upper(trim(p_application_code)) and lower(h.email)=lower(trim(p_email)) and h.approval_status='approved' order by coalesce(a.scheduled_for,a.assigned_at) desc $$;
revoke execute on function public.bct_handyman_assignments_for_app(text,text) from public,authenticated; grant execute on function public.bct_handyman_assignments_for_app(text,text) to anon;