-- Let authenticated property managers operate projects for properties in their own active portfolio.
drop policy if exists "BCT projects property manager select" on public.bct_projects;
create policy "BCT projects property manager select" on public.bct_projects for select to authenticated using(managed_property_id is not null and exists(select 1 from public.bct_managed_properties mp join public.bct_property_accounts pa on pa.id=mp.property_account_id where mp.id=bct_projects.managed_property_id and pa.auth_user_id=auth.uid() and pa.active and mp.active));
drop policy if exists "BCT projects property manager insert" on public.bct_projects;
create policy "BCT projects property manager insert" on public.bct_projects for insert to authenticated with check(project_market='multifamily' and managed_property_id is not null and exists(select 1 from public.bct_managed_properties mp join public.bct_property_accounts pa on pa.id=mp.property_account_id where mp.id=bct_projects.managed_property_id and pa.auth_user_id=auth.uid() and pa.active and mp.active));
drop policy if exists "BCT projects property manager update" on public.bct_projects;
create policy "BCT projects property manager update" on public.bct_projects for update to authenticated using(managed_property_id is not null and exists(select 1 from public.bct_managed_properties mp join public.bct_property_accounts pa on pa.id=mp.property_account_id where mp.id=bct_projects.managed_property_id and pa.auth_user_id=auth.uid() and pa.active and mp.active)) with check(project_market='multifamily' and managed_property_id is not null and exists(select 1 from public.bct_managed_properties mp join public.bct_property_accounts pa on pa.id=mp.property_account_id where mp.id=bct_projects.managed_property_id and pa.auth_user_id=auth.uid() and pa.active and mp.active));
create or replace function public.bct_user_owns_or_manages_project(p_project_id uuid) returns boolean language sql stable security invoker set search_path=public,auth as $$ select public.bct_user_owns_project(p_project_id) or exists(select 1 from public.bct_projects p join public.bct_managed_properties mp on mp.id=p.managed_property_id join public.bct_property_accounts pa on pa.id=mp.property_account_id where p.id=p_project_id and pa.auth_user_id=auth.uid() and pa.active and mp.active) $$;
revoke all on function public.bct_user_owns_or_manages_project(uuid) from public,anon;grant execute on function public.bct_user_owns_or_manages_project(uuid) to authenticated;
create or replace function public.bct_my_job_communications(p_project_id uuid) returns setof public.bct_job_communication_events language plpgsql security invoker set search_path=public,auth as $$ begin if auth.uid() is null then raise exception 'Authentication required';end if;if not(public.is_bct_admin() or public.bct_user_owns_or_manages_project(p_project_id) or public.bct_user_assigned_to_project(p_project_id)) then raise exception 'Not authorized for this BCT project';end if;return query select e.* from public.bct_job_communication_events e where e.project_id=p_project_id order by e.created_at;end $$;
create or replace function public.bct_send_job_message(p_project_id uuid,p_message text) returns uuid language plpgsql security invoker set search_path=public,auth as $$
declare v_uid uuid:=auth.uid();v_session uuid;v_role text;v_id uuid;begin if v_uid is null then raise exception 'Authentication required';end if;if nullif(btrim(coalesce(p_message,'')),'') is null then raise exception 'Message required';end if;if public.is_bct_admin() then v_role:='bct_admin';elsif exists(select 1 from public.bct_projects p join public.bct_managed_properties mp on mp.id=p.managed_property_id join public.bct_property_accounts pa on pa.id=mp.property_account_id where p.id=p_project_id and pa.auth_user_id=v_uid and pa.active and mp.active) then v_role:='property_manager';elsif public.bct_user_owns_project(p_project_id) then v_role:='homeowner';elsif public.bct_user_assigned_to_project(p_project_id) then v_role:='contractor';else raise exception 'Not authorized for this BCT project';end if;select id into v_session from public.bct_job_communication_sessions where project_id=p_project_id and status='active' order by created_at desc limit 1;if v_session is null then if not public.is_bct_admin() then raise exception 'BCT must activate communication for this job first';end if;insert into public.bct_job_communication_sessions(project_id,communication_mode,created_by) values(p_project_id,'in_app',v_uid) returning id into v_session;end if;insert into public.bct_job_communication_events(session_id,project_id,sender_role,event_type,body,created_by) values(v_session,p_project_id,v_role,'message',btrim(p_message),v_uid) returning id into v_id;return v_id;end $$;
