-- BCT-mediated Phase 1 communications foundation: job-tied messaging plus provider-ready proxy/recording evidence.
create table if not exists public.bct_job_communication_sessions(id uuid primary key default gen_random_uuid(),project_id uuid not null references public.bct_projects(id) on delete cascade,job_id uuid references public.bct_jobs(id) on delete cascade,assigned_contractor_id uuid,communication_mode text not null default 'in_app',status text not null default 'active',proxy_provider text,proxy_reference text,recording_enabled boolean not null default false,recording_notice_at timestamptz,recording_consent_at timestamptz,recording_reference text,created_by uuid default auth.uid(),created_at timestamptz not null default now(),ended_at timestamptz,constraint bct_comm_mode_ck check(communication_mode in('in_app','proxy_sms','proxy_voice')),constraint bct_comm_status_ck check(status in('active','ended')),constraint bct_recording_consent_ck check(not recording_enabled or (recording_notice_at is not null and recording_consent_at is not null)));
create table if not exists public.bct_job_communication_events(id uuid primary key default gen_random_uuid(),session_id uuid not null references public.bct_job_communication_sessions(id) on delete cascade,project_id uuid not null references public.bct_projects(id) on delete cascade,job_id uuid references public.bct_jobs(id) on delete cascade,sender_role text not null,event_type text not null,body text,provider_event_id text,created_by uuid default auth.uid(),created_at timestamptz not null default now(),constraint bct_comm_sender_ck check(sender_role in('bct_admin','homeowner','resident','property_manager','contractor','system')),constraint bct_comm_event_ck check(event_type in('message','arrival_notice','call_started','recording_notice','recording_consent','call_ended','system')));
alter table public.bct_job_communication_sessions enable row level security;
alter table public.bct_job_communication_events enable row level security;
drop policy if exists "Communication sessions admin only" on public.bct_job_communication_sessions;
create policy "Communication sessions admin only" on public.bct_job_communication_sessions for all to authenticated using(public.is_bct_admin()) with check(public.is_bct_admin());
drop policy if exists "Communication events admin only" on public.bct_job_communication_events;
create policy "Communication events admin only" on public.bct_job_communication_events for all to authenticated using(public.is_bct_admin()) with check(public.is_bct_admin());
create or replace function public.bct_my_job_communications(p_project_id uuid) returns setof public.bct_job_communication_events language plpgsql security invoker set search_path=public,auth as $$
begin if auth.uid() is null then raise exception 'Authentication required';end if;if not (public.is_bct_admin() or public.bct_user_owns_project(p_project_id) or public.bct_user_assigned_to_project(p_project_id)) then raise exception 'Not authorized for this BCT project';end if;return query select e.* from public.bct_job_communication_events e where e.project_id=p_project_id order by e.created_at;end $$;
revoke all on function public.bct_my_job_communications(uuid) from public,anon;
grant execute on function public.bct_my_job_communications(uuid) to authenticated;
create or replace function public.bct_send_job_message(p_project_id uuid,p_message text) returns uuid language plpgsql security invoker set search_path=public,auth as $$
declare v_uid uuid:=auth.uid();v_session uuid;v_role text;v_id uuid;
begin if v_uid is null then raise exception 'Authentication required';end if;if nullif(btrim(coalesce(p_message,'')),'') is null then raise exception 'Message required';end if;if public.is_bct_admin() then v_role:='bct_admin';elsif public.bct_user_owns_project(p_project_id) then v_role:='homeowner';elsif public.bct_user_assigned_to_project(p_project_id) then v_role:='contractor';else raise exception 'Not authorized for this BCT project';end if;select id into v_session from public.bct_job_communication_sessions where project_id=p_project_id and status='active' order by created_at desc limit 1;if v_session is null then if not public.is_bct_admin() then raise exception 'BCT must activate communication for this job first';end if;insert into public.bct_job_communication_sessions(project_id,communication_mode,created_by) values(p_project_id,'in_app',v_uid) returning id into v_session;end if;insert into public.bct_job_communication_events(session_id,project_id,sender_role,event_type,body,created_by) values(v_session,p_project_id,v_role,'message',btrim(p_message),v_uid) returning id into v_id;return v_id;end $$;
revoke all on function public.bct_send_job_message(uuid,text) from public,anon;
grant execute on function public.bct_send_job_message(uuid,text) to authenticated;
